### ISSUE TITLE
No content in thee Readme.md file

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/ecommerce-app-predators-bn#12]
There's not enough content in the Readme.md file to guide people who are looking at your repo or even just for reference.

**Comment by mukunzidd** [comment]
@chanceDira can you assign this to someone ASAP? Populating the readme.md with useful information.

**Comment by chanceDira** [comment]
> @chanceDira can you assign this to someone ASAP? Populating the readme.md with useful information. 

@Vanessa-bitega is working on it.
